# Generated by Django 5.2.2 on 2025-06-25 10:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название проекта')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст проекта')),
                ('img', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Фото проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='ЧПУ-ссылка')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
