# Generated by Django 5.2.2 on 2025-07-22 12:17

import ckeditor.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Фото проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_finish', models.BooleanField(default=False, verbose_name='Выполнен проект или нет')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Ключевой проект или нет')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='ЧПУ-ссылка')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название проекта')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст проекта')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Локация проекта')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='projects.projects')),
            ],
            options={
                'verbose_name': 'Проект Translation',
                'db_table': 'projects_projects_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
