# Generated by Django 5.2.2 on 2025-06-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='img',
            new_name='image',
        ),
        migrations.AddField(
            model_name='projects',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Локация проекта'),
        ),
    ]
