# Generated by Django 5.2.2 on 2025-06-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_img_projects_image_projects_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Текущий проект или нет'),
        ),
    ]
