# Generated by Django 5.2.2 on 2025-06-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Ключевой проект или нет'),
        ),
    ]
