# Generated by Django 5.2.2 on 2025-06-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='is_current',
        ),
        migrations.AddField(
            model_name='projects',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='Выполнен проект или нет'),
        ),
    ]
