# Generated by Django 5.2.2 on 2025-06-24 10:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Имя проекта')),
                ('image', models.ImageField(upload_to='companies/', verbose_name='Лого компании')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['-created_at'],
            },
        ),
    ]
