# Generated by Django 5.2.2 on 2025-06-24 12:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст компании'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Имя компании'),
        ),
    ]
