# Generated by Django 5.2.2 on 2025-06-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_alter_companies_text_alter_companies_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на компанию'),
        ),
    ]
