# Generated by Django 5.2.2 on 2025-06-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='имя фото'),
        ),
    ]
