# Generated by Django 5.2.2 on 2025-07-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
    ]
