# Generated by Django 5.2.2 on 2025-06-13 11:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Имя проекта')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Фото проекта')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Фото'),
        ),
    ]
