# Generated by Django 5.2.2 on 2025-07-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_сontactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='СontactForm',
            new_name='ContactForm',
        ),
    ]
