# Generated by Django 5.2.2 on 2025-06-16 06:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=250, null=True, verbose_name='Автор')),
                ('image', models.ImageField(upload_to='comment/', verbose_name='Фото')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
    ]
