# Generated by Django 5.2.2 on 2025-06-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='videosPhoto/'),
        ),
    ]
