# Generated by Django 5.2.2 on 2025-06-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_awards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
