# Generated by Django 5.2.2 on 2025-06-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
