# Generated by Django 5.2.2 on 2025-06-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmain',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videosAbout/', verbose_name='Видео'),
        ),
    ]
