# Generated by Django 5.2.2 on 2025-06-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutmain_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmain',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
