# Generated by Django 5.2.2 on 2025-06-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutmain_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название')),
                ('number', models.CharField(blank=True, max_length=250, null=True, verbose_name='число')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'О нас статистика',
                'verbose_name_plural': 'Статистики',
                'ordering': ['-created_at'],
            },
        ),
    ]
