# Generated by Django 5.2.2 on 2025-06-23 06:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=250, null=True, verbose_name='Автор')),
                ('position', models.CharField(blank=True, max_length=250, null=True, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='comment/', verbose_name='Фото')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
